version: '3'

services:
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty12345
      MYSQL_DATABASE: edufund_tes
      MYSQL_USER: root
      MYSQL_PASSWORD: qwerty12345
  

  adminer:
    image: adminer
    restart: always
    ports:
      - 3306:3306
  